<?php
/**
 * Message
 *
 * PHP version 5
 *
 * @category Class
 * @package  KhipuChaski
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KhipuChaski\Model;

use \ArrayAccess;
/**
 * Message Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     KhipuChaski
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Message implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'subject' => 'string',
        'recipient_id_set' => 'string[]',
        'body' => 'string',
        'msg_properties' => '\KhipuChaski\Model\MsgProperty[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'subject' => 'subject',
        'recipient_id_set' => 'recipientIdSet',
        'body' => 'body',
        'msg_properties' => 'msgProperties'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'subject' => 'setSubject',
        'recipient_id_set' => 'setRecipientIdSet',
        'body' => 'setBody',
        'msg_properties' => 'setMsgProperties'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'subject' => 'getSubject',
        'recipient_id_set' => 'getRecipientIdSet',
        'body' => 'getBody',
        'msg_properties' => 'getMsgProperties'
    );
  
    
    /**
      * $subject Asunto de mensaje
      * @var string
      */
    protected $subject;
    
    /**
      * $recipient_id_set Lista de identificadores de receptores del mensaje
      * @var string[]
      */
    protected $recipient_id_set;
    
    /**
      * $body Cuerpo del mensaje
      * @var string
      */
    protected $body;
    
    /**
      * $msg_properties Lista de propiedades del mensaje
      * @var \KhipuChaski\Model\MsgProperty[]
      */
    protected $msg_properties;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->subject = $data["subject"];
            $this->recipient_id_set = $data["recipient_id_set"];
            $this->body = $data["body"];
            $this->msg_properties = $data["msg_properties"];
        }
    }
    
    /**
     * Gets subject
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }
  
    /**
     * Sets subject
     * @param string $subject Asunto de mensaje
     * @return $this
     */
    public function setSubject($subject)
    {
        
        $this->subject = $subject;
        return $this;
    }
    
    /**
     * Gets recipient_id_set
     * @return string[]
     */
    public function getRecipientIdSet()
    {
        return $this->recipient_id_set;
    }
  
    /**
     * Sets recipient_id_set
     * @param string[] $recipient_id_set Lista de identificadores de receptores del mensaje
     * @return $this
     */
    public function setRecipientIdSet($recipient_id_set)
    {
        
        $this->recipient_id_set = $recipient_id_set;
        return $this;
    }
    
    /**
     * Gets body
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }
  
    /**
     * Sets body
     * @param string $body Cuerpo del mensaje
     * @return $this
     */
    public function setBody($body)
    {
        
        $this->body = $body;
        return $this;
    }
    
    /**
     * Gets msg_properties
     * @return \KhipuChaski\Model\MsgProperty[]
     */
    public function getMsgProperties()
    {
        return $this->msg_properties;
    }
  
    /**
     * Sets msg_properties
     * @param \KhipuChaski\Model\MsgProperty[] $msg_properties Lista de propiedades del mensaje
     * @return $this
     */
    public function setMsgProperties($msg_properties)
    {
        
        $this->msg_properties = $msg_properties;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
